<a href="https://colab.research.google.com/github/rian-souza/Airbnb-Inteligencia-de-Dados-Jul-Dez-2023/blob/main/Airbnb_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_csv("/content/Airbnb_site_hotel new.csv", dtype=str)

df['price'] = df['price'].str.replace(',', '.').str.replace('[^0-9.]', '', regex=True).astype(float)

df["host Certification"] = pd.to_numeric(df["host Certification"], errors='coerce')
df["host Certification"] = df["host Certification"].fillna(df["host Certification"].mean())
df["room_type"] = df["room_type"].fillna(df["room_type"].mode()[0])
df["host total listings count"] = df["host total listings count"].fillna(df["host total listings count"].mode()[0])
df["consumer"] = df["consumer"].fillna(df["consumer"].mode()[0])

df["host response rate"] = df["host response rate"].str.replace(",", ".").str.rstrip("%").astype(float)
df["host acceptance rate"] = df["host acceptance rate"].str.replace(",", ".").str.rstrip("%").astype(float)

df["price"] = df["price"].astype(float)

df.isnull().sum()

id                               0
name                             0
host_id                          0
host_name                        0
city                             0
price                         5424
reply time                   19319
guest favourite                  0
host since                       0
host Certification               0
room_type                        0
host total listings count        0
consumer                         0
total reviewers number           0
accommodates                     0
bathrooms                        0
bedrooms                         0
beds                             0
listing number                   0
host response rate               0
host acceptance rate             0
sales                            0
area                             0
dtype: int64